import { Container } from "@/lib/mui/material";
import Navbar from "@/lib/components/navbar";
import { MuiSetup } from "./MuiSetup";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <MuiSetup>
          <Navbar />

          <Container>{children}</Container>
        </MuiSetup>
      </body>
    </html>
  );
}
